name: CI Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [vote, result, worker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/charanprajwal/example-voting-app-ci/${{ matrix.service }}:latest -t ghcr.io/charanprajwal/example-voting-app-ci/${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}

      - name: Push Docker images (latest and commit SHA)
        run: |
          docker push ghcr.io/charanprajwal/example-voting-app-ci/${{ matrix.service }}:latest
          docker push ghcr.io/charanprajwal/example-voting-app-ci/${{ matrix.service }}:${{ github.sha }}

      - name: Get image digest
        id: get_digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/charanprajwal/example-voting-app-ci/${{ matrix.service }}:${{ github.sha }})
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Checkout CD repo
        uses: actions/checkout@v4
        with:
          repository: CHARANPRAJWAL/example-voting-app-CD
          token: ${{ secrets.CD_REPO_TOKEN }}
          path: cd-repo

      - name: Update image tag in CD repo
        run: |
          # Update the correct manifest file for each service
          manifest_file="cd-repo/${{ matrix.service }}-manifest.yaml"
          sed -i "s|image:.*|image: ghcr.io/charanprajwal/example-voting-app-ci/${{ matrix.service }}@${{ steps.get_digest.outputs.digest }}|" "$manifest_file"
          cd cd-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$manifest_file"
          git commit -m "Update ${{ matrix.service }} image to ${{ steps.get_digest.outputs.digest }}"
          git push